"""
The Annals of Elysal — 8,000 Years of History
Compiled by Thandrik Ironquill, Keeper of the Annals

Each age spans roughly 1,000 years. Within each age are 10 centuries.
"""

ANNALS_INTRO = """In the deepest vaults beneath the mountain fortress of Karak Thandrim, an ancient dwarf sits surrounded by towers of parchment, rivers of ink, and the weight of eight thousand years. His name is Thandrik Ironquill — the last Keeper of the Annals.

For over three centuries, Thandrik has dedicated his life to a singular obsession: chronicling every war, every treaty, every birth and death and betrayal that has shaped the world of Elysal. His predecessors began this work in the final days of the Seventh Age, when the Conclave of Sages decreed that the world's memory must not be left to the unreliable tongues of bards and the crumbling stones of ruins.

The Annals are not merely a history — they are a living archive, growing with each passing day as scholars, adventurers, and witnesses contribute their accounts. Some entries are meticulously verified across multiple sources. Others are legends, half-remembered and debated. Thandrik records them all, because even myths shape the course of nations.

"The past is not dead," Thandrik is fond of saying, stroking his iron-grey beard. "It is not even past. Every sword drawn today was forged in yesterday's fire."

You now stand before the Annals. Eight ages of wonder, horror, triumph, and ruin await you. Read carefully — for those who forget the past are doomed to repeat it, and in Elysal, repetition tends to involve dragons."""

AGES = [
    {
        "number": 1,
        "name": "The Age of First Light",
        "year_start": 1,
        "year_end": 1000,
        "description": """The Age of First Light marks the dawn of recorded civilization in Elysal. Before this era, only fragments and oral traditions survive — whispers of a primordial world shaped by the Titans, colossal beings of elemental power who carved the continents and filled the seas.

The First Light refers to the moment the elder races — elves, dwarves, and the ancient dragonborn — emerged from the chaos of the Titan Wars and began to build. The elves raised their first crystal spires in what would become the Moonlit Court. The dwarves delved deep into the mountains of Karak Thandrim. The dragonborn established their empire of Drakarath across the Crimson Sands.

This was an age of wonder and innocence, when magic flowed freely and the barriers between the mortal world and the Feywild were gossamer-thin. But it was also an age of terrible naivety — the elder races did not yet understand the darkness that lurked beneath the surface of the world, waiting to rise.""",
        "centuries": [
            {"number": 1, "name": "First Century", "description": "The Awakening. The elder races emerge from the aftermath of the Titan Wars. The first settlements are founded. The elves discover the Moonlit Court, a place where the boundary between worlds is thinnest. The dwarves begin the Great Delving of Karak Thandrim.",
             "stories": [
                {"title": "The Last Titan Falls", "content": "The earth shook for seven days when Gorath the Mountainbreaker, last of the great Titans, was finally brought low. It took the combined might of three elven archmages, a dwarven legion, and a young dragonborn warlord named Kaelith to pierce the Titan's heart of living stone.\n\nGorath's death scream carved the Shattered Coast — a jagged wound in the continent that would become one of Elysal's most treacherous coastlines. His blood, molten and golden, seeped into the earth and formed the veins of precious ore that the dwarves would later mine for millennia.\n\nKaelith, barely more than a hatchling by dragonborn standards, stood atop the fallen Titan's chest and planted a banner. 'The age of being shaped is over,' he declared. 'Now begins the age of shaping.'\n\nHistorians debate whether Kaelith truly spoke these words or if they were attributed to him later. Thandrik notes that dragonborn of that era were more inclined to roar than make speeches."},
                {"title": "The First Delving", "content": "When the dwarf king Borin Deepaxe struck his pickaxe into the roots of Mount Thandrim, he expected to find stone. Instead, he found a vast cavern already carved — not by any mortal hand, but by the slow patience of underground rivers over millions of years.\n\nThe cavern was enormous. Luminous crystals dotted the ceiling like frozen stars. A river of pure meltwater ran through its heart. Borin wept — which, for a dwarf, is the highest form of architectural appreciation.\n\n'We do not carve this mountain,' Borin told his people. 'We merely finish what the world began.'\n\nOver the next century, the dwarves would transform this natural wonder into Karak Thandrim, the Mountain Throne. Its halls would eventually stretch for miles, housing a civilization of over fifty thousand dwarves. But in those first days, it was simply a cave, a river, and a king with a vision."}
            ]},
            {"number": 2, "name": "Second Century", "description": "The Age of Builders. The three elder races establish their great civilizations. Trade routes are forged between the Moonlit Court, Karak Thandrim, and Drakarath. The first common tongue, called Eldermark, is developed by scholars of all three races.",
             "stories": [
                {"title": "The Eldermark Accords", "content": "Communication between the elder races was, at first, a comedy of errors. Elvish was too fluid and metaphorical for dwarven tongues. Dwarvish was too guttural and precise for elven sensibilities. And Draconic was simply terrifying to everyone who wasn't a dragonborn.\n\nThe solution came from an unlikely source: a half-deaf elven linguist named Illithari who, owing to her condition, had developed an extraordinary written notation system. She proposed a common written language that borrowed the precision of Dwarvish grammar, the expressiveness of Elvish vocabulary, and the directional markers of Draconic.\n\nThe resulting language — Eldermark — was elegant, efficient, and despised by purists of all three races. Which, Illithari noted, meant she'd done her job perfectly.\n\nThe Eldermark Accords, signed in the neutral territory that would later become Valdris, established this common tongue for all diplomatic and trade purposes. It remains the foundation of the Common tongue spoken today."},
                {"title": "The Bridge of Three Fires", "content": "The first great trade route between the three civilizations required crossing the Dragonmaw Pass — a narrow, wind-howling gap between two mountains that was perpetually shrouded in ice storms.\n\nThe solution was a marvel of combined engineering. Dwarven masons carved the bridge from living mountain stone. Elven enchanters wove weather-warding spells into its surface. Dragonborn fire-shapers installed three eternal braziers that burned without fuel, melting the ice and lighting the way.\n\nThe Bridge of Three Fires stood for over four thousand years before it was destroyed in the wars of the Fifth Age. Even its ruins remain a popular pilgrimage site, a reminder of what the races could accomplish when they worked together — something they would struggle to remember in the ages to come."}
            ]},
            {"number": 3, "name": "Third Century", "description": "The Discovery of the Feywild Crossings. Elven explorers map the thin places between the mortal world and the Feywild. The first recorded contact with fey creatures. Some crossings prove dangerous, leading to the establishment of the Wardens.",
             "stories": [
                {"title": "The Dancer at the Threshold", "content": "The elven scout Aerith Moonwhisper was the first to document a Feywild Crossing in detail. She described a glade where the grass grew in impossible spirals, where flowers bloomed and died in the space of a breath, and where a figure stood at the very edge of perception — dancing.\n\n'I watched it for what I believed was an hour,' Aerith wrote in her journal. 'When I returned to camp, three days had passed. My companions had given me up for dead. I told them what I had seen. They told me I had been standing at the edge of the glade the entire time, swaying gently, with my eyes open but unseeing.'\n\nThe figure — later identified as one of the Pale Dancers, powerful fey spirits — had not harmed Aerith. But it had taken three days of her life as casually as a child picks a flower. The encounter led to the formal establishment of the Wardens, guardians trained to monitor and protect the Feywild Crossings."},
                {"title": "The Treaty of Thorns", "content": "The first formal agreement between the mortal races and the fey courts was negotiated by an elven diplomat named Caelindra and a fey lord known only as the Thornking.\n\nThe negotiations lasted a year and a day — the fey insisted on this timeframe for reasons they considered obvious and everyone else considered infuriating. The resulting treaty established boundaries: the fey would not cross uninvited into mortal lands, and mortals would not enter the Feywild without permission.\n\nThe treaty was written on a living leaf that never wilted, and sealed with a drop of blood from each signatory. Caelindra noted that the Thornking smiled throughout the entire ceremony. She found this deeply unsettling.\n\n'The fey do not make treaties,' she wrote afterward. 'They make games. And I am not entirely sure we understand the rules.'"}
            ]},
            {"number": 4, "name": "Fourth Century", "description": "The Rise of Human Civilization. Humans, younger than the elder races but remarkably adaptable, begin to establish their own kingdoms. The first human cities — Valdris and Stormreach — are founded on the coasts.",
             "stories": [
                {"title": "The Coming of Men", "content": "The elder races had always known about humans. They just hadn't taken them very seriously.\n\nElves considered them charming but fleeting — like butterflies, beautiful and brief. Dwarves found them useful for tasks that required more flexibility than stone and less patience than mining. The dragonborn barely noticed them at all.\n\nBut humans had something the elder races lacked: urgency. With lifespans measured in decades rather than centuries, humans built with a frantic energy that was equal parts inspiring and alarming. In the space of a single elven generation, humans went from scattered tribes to walled cities.\n\nValdris, founded by a human woman named Sera Tidecaller, grew from a fishing village to a trade hub in thirty years. When the elven ambassador arrived to establish diplomatic relations, he was stunned to find a city of ten thousand with a functioning navy.\n\n'How did you do this so quickly?' he asked.\n\n'Quickly?' Sera replied. 'My grandmother died waiting for this port. We have no time to be slow.'"},
                {"title": "The Stormreach Compact", "content": "Stormreach Harbour was not founded — it was seized. A coalition of human sailors, led by the legendary Captain Aldric Stormborn, wrested control of the natural harbour from a clutch of sea drakes that had nested there for centuries.\n\nThe battle lasted three days and cost twelve ships. Aldric's flagship, the Iron Dawn, was sunk twice — and raised twice, because Aldric was too stubborn to accept that sunken ships should stay sunken.\n\nThe Stormreach Compact, signed among the surviving captains, established one of the first human democratic institutions: a council of ship-captains who would govern the port collectively. No kings, no lords — just the people who had bled for the harbour.\n\nThis tradition of elected governance would influence human politics for millennia, though future generations would frequently forget that democracy was invented by pirates."}
            ]},
            {"number": 5, "name": "Fifth Century", "description": "The Golden Meridian. A period of unprecedented peace and prosperity. All four major races cooperate in building the Eternal Bazaar, a trade city that belongs to no nation. Magic and technology advance rapidly.",
             "stories": [
                {"title": "The Eternal Bazaar Opens", "content": "The Eternal Bazaar was conceived as an impossible idea: a city that belonged to no one, governed by no king, and open to all.\n\nIt was built on a convergence of ley lines — rivers of magical energy that flowed beneath the surface of Elysal. Elven mages stabilized the ley lines. Dwarven architects carved the foundations from enchanted stone that repaired itself. Human merchants organized the trade routes. Dragonborn guards patrolled the walls.\n\nOn the day the Bazaar opened its gates, merchants from every corner of Elysal poured through. Within a month, you could buy silks from the Moonlit Court, weapons from Karak Thandrim, spices from Drakarath, and fresh fish from Stormreach — all in the same afternoon.\n\nThe Bazaar had one rule, carved into every archway in every language: 'No blood shall be spilled within these walls.' Violators were not punished by guards. The ley lines themselves seemed to enforce the edict — anyone who drew a weapon with violent intent found it suddenly, inexplicably too heavy to lift."},
                {"title": "Illindra's Theorem", "content": "The archmage Illindra of Valdris made a discovery that would reshape the understanding of magic: spells were not powered by the caster's will alone, but by the ambient magical energy of the world itself.\n\nThis seems obvious now, but at the time, the prevailing theory was that magic came entirely from within — that mages were simply born with an internal reservoir of power. Illindra proved that mages were more like channels than reservoirs, drawing energy from ley lines and the natural world.\n\nThe implications were revolutionary. It meant magic could be studied systematically. It meant ley lines could be mapped. It meant, terrifyingly, that the world's magical energy was finite — and that it was slowly, imperceptibly depleting.\n\nIllindra's Theorem was celebrated for its brilliance and feared for its implications. The Conclave of Sages awarded her their highest honor and then immediately classified her research. Some truths, they decided, were too dangerous for the public."}
            ]},
            {"number": 6, "name": "Sixth Century", "description": "The first signs of darkness. Miners in Karak Thandrim breach an ancient sealed chamber and release something that was never meant to be found. Strange disappearances begin across the continent.",
             "stories": [
                {"title": "The Breach", "content": "Foreman Durik had been mining the deep veins of Karak Thandrim for forty years. He knew the sound of every type of stone — the ring of granite, the dull thud of limestone, the metallic echo of ore veins. So when his pickaxe struck something that sounded like nothing at all — a complete absence of sound, a void where an echo should have been — he knew something was wrong.\n\nBeyond the wall was a chamber sealed with sigils so old they predated dwarvish writing. The air that rushed out was cold — not the cold of underground depths, but a metaphysical cold, as if warmth itself had been forbidden in that place.\n\nDurik sent word to the king. The king sent scholars. The scholars sent for the elves. By the time everyone arrived, three miners had gone missing. Their pickaxes were found arranged in a perfect circle around the breach, standing upright on their own.\n\nNo bodies were ever recovered.\n\nThe chamber was resealed within a week, but the damage was done. Something had been released. Something patient."},
                {"title": "The Vanishing of Thornwick", "content": "Thornwick was a village of four hundred souls, nestled in a valley near the Whispering Grove. One autumn morning, a traveling merchant arrived to find the village completely empty.\n\nNot abandoned — empty. Breakfast porridge still bubbled over cold fires. Laundry hung on lines. A child's doll sat in the middle of the village square, positioned as if someone had set it down for just a moment.\n\nThe merchant searched every building. He found no signs of struggle, no blood, no packed belongings. Four hundred people had simply ceased to exist between one heartbeat and the next.\n\nInvestigations revealed nothing. Divination magic returned blank results — not failures, but genuine blanks, as if the universe itself refused to remember what had happened.\n\nOver the next decade, seven more communities would vanish in the same impossible way."}
            ]},
            {"number": 7, "name": "Seventh Century", "description": "The Shadow Stirs. A cult dedicated to an entity known only as the Hollow emerges across multiple races. Tensions rise between nations as trust erodes. The first Shadow War begins.",
             "stories": [
                {"title": "The Cult of the Hollow", "content": "They called themselves the Embrace, and they worshipped nothing — literally. The entity they served was not a god, not a demon, not any creature that could be named or comprehended. It was an absence. A hole in the fabric of reality shaped like a hunger.\n\nThe Cult of the Hollow recruited from all races and all walks of life. Kings and beggars, warriors and scholars — the Hollow's call was democratic in its horror. Those who heard it described a sound like a vast, empty room echoing with their own deepest fears.\n\nThe cult's goal was simple and terrifying: to undo. Not to destroy — destruction implies something remains. The Hollow sought to make things never-have-been. To erase not just people and places, but the memory of people and places, until even history forgot they existed.\n\nThe vanished villages of the Sixth Century had been test runs."},
                {"title": "The Battle of Ashenmoor", "content": "The first open battle of the Shadow War was fought in the Ashenmoor Swamps, where a combined force of human and dwarven soldiers cornered a Hollow cult cell that had been abducting villagers.\n\nCommander Elara Brightshield led the assault with three hundred soldiers. She expected a fight against cultists — desperate zealots with makeshift weapons. What she found was far worse.\n\nThe cultists had learned to channel the Hollow's power. They didn't fight with swords or spells. They fought with erasure. Soldiers touched by the Hollow's energy simply ceased — their armor clattered empty to the ground, and their comrades couldn't remember their names.\n\nOf three hundred soldiers, one hundred and twelve returned. They reported the battle as a victory, but the reports contained gaps — references to people and events that no one could recall clearly, as if the memories had been partially dissolved.\n\nElara herself survived, though she was haunted for the rest of her life by the certainty that she had entered the swamp with a locket around her neck — a locket she could no longer describe, containing a portrait she could no longer remember."}
            ]},
            {"number": 8, "name": "Eighth Century", "description": "The Shadow War escalates. The Hollow breaches the Feywild Crossings, corrupting fey creatures into twisted servants. The Moonlit Court seals itself away. Alliances fracture under paranoia.",
             "stories": [
                {"title": "The Sealing of the Moonlit Court", "content": "Queen Lyrianthe of the Moonlit Court made the most controversial decision of the First Age: she sealed the elven homeland behind an impenetrable magical barrier, cutting off all contact with the outside world.\n\nHer reasoning was brutally pragmatic. The Hollow had begun corrupting the Feywild Crossings, and the Moonlit Court sat atop the largest cluster of crossings on the continent. If the Hollow reached the Feywild through the Court, it wouldn't just threaten Elysal — it would threaten the entire fabric of reality.\n\n'I am not abandoning our allies,' Lyrianthe wrote in her final message to the other races. 'I am protecting them from what we would become if the Hollow touched our gates.'\n\nThe barrier held for two centuries. But the damage to inter-racial relations was immediate and lasting. The dwarves called it betrayal. The humans called it cowardice. The dragonborn said nothing — which, from dragonborn, was the most damning response of all."},
                {"title": "The Corruption of the Thornwood", "content": "When the Hollow's influence reached the Feywild Crossings in the Thornwood Forest, the transformation was not dramatic — it was insidious.\n\nThe trees didn't die. They continued to grow. But they grew wrong — in spirals and angles that hurt to look at, reaching toward a sun that wasn't there. Animals in the forest didn't flee. They stood perfectly still, arranged in patterns that seemed random until you looked at them from above and saw they formed a shape — a hole. Always a hole.\n\nThe Wardens who monitored the Thornwood crossings were the first to succumb. One by one, they stopped reporting in. When a search party finally entered the forest, they found the Wardens alive and lucid — but changed. They spoke normally, they followed orders, they answered questions correctly. But when asked to describe the color of the sky, they couldn't.\n\nNot wouldn't. Couldn't. The concept of blue had been removed from their minds, as neatly as a surgeon removes a splinter."}
            ]},
            {"number": 9, "name": "Ninth Century", "description": "The Darkest Hour. The Hollow manifests a physical form at the Abyssal Rift. The remaining free nations mount a desperate alliance. Heroes rise from every race to stand against oblivion.",
             "stories": [
                {"title": "The Abyssal Rift", "content": "For eight centuries, the Hollow had been an abstract threat — an unseen force that erased from the shadows. But in the spring of Year 834 of the First Age, it became real.\n\nThe Abyssal Rift tore open in the badlands east of Karak Thandrim — a wound in reality itself, miles across, deeper than any abyss. Looking into it was not like looking into darkness. It was like looking at a space where looking itself had no meaning.\n\nFrom the Rift came silence. Not quiet — silence. An active, hungry silence that consumed sound. Birds fell dead in the air within a mile of the Rift. Trees crumbled to dust. And at the center of it all, something stood. Something that was nothing. The Hollow had given itself a shape, and the shape was absence wearing a crown.\n\nThe remaining free nations had no choice. The dwarves, humans, and dragonborn formed the Alliance of the Last Dawn. Even the Moonlit Court lowered its barriers for the first time in two centuries, sending a contingent of their most powerful mages.\n\nThe final war for Elysal's existence had begun."},
                {"title": "The Gathering of Heroes", "content": "They came from everywhere. Not just armies — individuals. People who had no business being on a battlefield but came anyway because the alternative was a world that forgot they ever existed.\n\nBorin Anvilhand, a dwarven smith who forged a hammer that could strike what couldn't be touched. Seraphiel, a human cleric who had lost her faith but fought with a fury that shamed the devout. Kaelith Reborn, a dragonborn who claimed descent from the Kaelith who slew the last Titan — and wielded fire that burned even the void. And Thornwhisper, a defected Warden whose mind the Hollow had touched but not broken, who could see the patterns in its attacks.\n\nThey were not an army. They were a last prayer given legs and weapons.\n\nThandrik notes that of the forty-seven named heroes who marched on the Abyssal Rift, only eleven returned. He has recorded the names of all forty-seven. The Hollow may erase villages from memory, but the Annals remember."}
            ]},
            {"number": 10, "name": "Tenth Century", "description": "The Sealing. The heroes sacrifice everything to close the Abyssal Rift and banish the Hollow. The First Age ends not with victory but with survival. The world begins to heal, scarred but standing.",
             "stories": [
                {"title": "The Sealing of the Rift", "content": "The details of how the Abyssal Rift was sealed are, ironically, incomplete. Several of the accounts contradict each other, and some pages of the original records appear to have been — fittingly — erased.\n\nWhat is known: the eleven surviving heroes entered the Rift. A ritual was performed that required the willing sacrifice of seven of them — not their lives, but their existence. They chose to be unmade so that the Rift could be unmade.\n\nSeraphiel was among the seven. Her last recorded words were: 'I found my faith. It was not in any god. It was in the stubborn refusal to be forgotten.'\n\nThe Rift collapsed in on itself over the course of three days. The silence receded. Color returned to the blighted lands. Birds sang again — cautiously at first, as if testing whether sound was allowed.\n\nFour heroes walked out of where the Rift had been. They were aged beyond their years, their hair white, their eyes haunted. When asked what they had seen inside, all four gave the same answer: 'Nothing. And it was everything.'\n\nThandrik has preserved their names. The names of the seven who were unmade are recorded in a sealed section of the Annals, written in a code that prevents the Hollow — should it ever stir again — from finding and finishing what it started."},
                {"title": "The Dawn of the Second Age", "content": "The world that emerged from the Shadow War was not the world that had entered it. The Moonlit Court was reopened but diminished. Karak Thandrim had lost a third of its population. The dragonborn empire of Drakarath was shattered into feuding clans. And humans, as always, were already rebuilding.\n\nThe elder races looked upon the wreckage of the First Age and saw failure. Humans looked upon the same wreckage and saw opportunity. This fundamental difference in perspective would define the next seven thousand years.\n\nAt a summit held in the ruins of the Eternal Bazaar, the surviving leaders agreed on one thing: the Annals must be established. Every event must be recorded. Every name must be preserved. The Hollow had shown them that the true enemy was not death but forgetting.\n\nAnd so the first Keeper of the Annals was appointed — a dwarven scholar named Grundi Ironquill, great-great-great-grandfather of Thandrik himself. The quill had passed through the family for every generation since.\n\nThe Second Age had begun."}
            ]}
        ]
    },
    {
        "number": 2,
        "name": "The Age of Shattered Crowns",
        "year_start": 1001,
        "year_end": 2000,
        "description": """The Second Age earned its grim name within its first century. With the great alliance that defeated the Hollow dissolved, the races of Elysal turned upon each other with a ferocity that shocked even the most cynical historians.

The root cause was simple: power vacuums. The Shadow War had destroyed or weakened every major institution. Kingdoms that had stood for centuries were reduced to ruins. The survivors, traumatized and distrustful, clutched at whatever power they could find — and fought anyone who tried to take it.

Crown after crown rose and fell. Dynasties lasted generations in the First Age; in the Second, some lasted barely a decade. Wars were fought over trade routes, over territory, over ancient grudges that the Shadow War had merely paused rather than resolved.

Yet this age of conflict also produced extraordinary individuals — warlords and peacemakers, tyrants and liberators, all struggling to impose their vision on a world that refused to sit still. By the age's end, the political map of Elysal had been redrawn entirely, and the foundations of the modern nations had been laid in blood and compromise.""",
        "centuries": [
            {"number": 1, "name": "First Century", "description": "The Fracturing. Old alliances collapse within decades of the Hollow's defeat. Border disputes erupt between dwarven holds and human settlements. The dragonborn clans war among themselves for control of Drakarath's remnants.",
             "stories": [
                {"title": "The Betrayal at Ironbridge", "content": "The alliance between Karak Thandrim and the human city of Stormreach had survived the Shadow War intact. It did not survive peacetime.\n\nThe dispute was over mining rights to the Silvervein Mountains — rich deposits of mithril that both nations claimed. Negotiations broke down when a dwarven delegation was attacked on the Ironbridge, the ancient crossing that connected the two territories.\n\nEach side blamed the other. The dwarves claimed human bandits had ambushed their envoys. The humans claimed the dwarves had staged the attack to justify military action. Modern scholars, examining the evidence, believe a third party — likely remnant Hollow cultists — orchestrated the incident specifically to fracture the alliance.\n\nThey succeeded. The Ironbridge War lasted twelve years and killed thousands on both sides. The bridge itself was destroyed in the final battle — the same bridge that had stood since the Second Century of the First Age, a symbol of cooperation reduced to rubble by paranoia."},
                {"title": "The Dragon Clans Divide", "content": "The dragonborn empire of Drakarath had been governed by a single Dragon Throne for all of the First Age. When the last Empress, Vyratha Flamecrown, died without an heir during the Shadow War, the empire shattered into seven clans, each led by a warlord who claimed the right to rule.\n\nThe resulting civil war — known as the Sevenfold Flame — consumed the Crimson Sands for a generation. Cities burned. Libraries were destroyed. Ancient artifacts were lost.\n\nBy the war's end, only three clans remained standing: the Emberclaw, the Ashscale, and the Stormwing. They divided the territory into three domains and signed a truce that was less a peace treaty and more a mutual acknowledgment that they were too exhausted to keep fighting.\n\nThe Dragon Throne itself was melted down and reforged into three identical lesser thrones — a pragmatic solution that satisfied no one, which is generally the sign of a successful compromise."}
            ]},
            {"number": 2, "name": "Second Century", "description": "The Warlord Era. Powerful individuals seize control across the continent. The most famous — Korvath the Unifier and Queen Valeria of Valdris — represent opposite approaches: conquest versus diplomacy.",
             "stories": [
                {"title": "Korvath's March", "content": "Korvath was not born to power. He was born in a ditch outside a burning village, the son of refugees who died before he could walk. Raised by a mercenary company, he learned three things: how to fight, how to lead, and how to make people afraid.\n\nBy age thirty, he commanded an army of twelve thousand — not through inheritance or legitimacy, but through the simple, brutal calculus of being better at war than anyone else. His March, as it came to be known, swept across the northern territories in a single campaign season, conquering seven city-states and three minor kingdoms.\n\nKorvath was not cruel — or rather, he was precisely as cruel as he needed to be. Cities that surrendered were treated fairly. Cities that resisted were made examples. The distinction was clear, and after the first two examples, most cities chose surrender.\n\nHis empire lasted forty years — impressive for the Second Age, but it collapsed within a decade of his death, because Korvath had built a kingdom around a man rather than an idea."},
                {"title": "The Valdris Accords", "content": "While Korvath conquered through force, Queen Valeria of Valdris conquered through paper. Her weapon was diplomacy, and her battlefield was the negotiating table.\n\nValeria recognized that the city-states of the southern coast shared more interests than grievances. They all needed safe trade routes. They all feared northern warlords. They all wanted autonomy. So she proposed something unprecedented: a voluntary federation.\n\nThe Valdris Accords were signed by fourteen coastal city-states, creating the Tideborn Confederacy. Each city retained its own governance but contributed to a shared navy, a shared trade currency, and a shared defense pact.\n\nSkeptics predicted the Confederacy would last a decade at most. It lasted for the remainder of the age — and its principles of voluntary cooperation would influence governance across Elysal for millennia.\n\nValeria herself lived to the age of ninety-three, which in the Second Age was practically immortal. Her last words were reportedly: 'I told you it would work.'"}
            ]},
            {"number": 3, "name": "Third Century", "description": "The Mage Wars. With the rediscovery of Illindra's Theorem, competing schools of magic battle for dominance. The Silver Tower and the Obsidian Academy wage a cold war that regularly turns hot.",
             "stories": [
                {"title": "The Duel of Silver and Obsidian", "content": "The rivalry between the Silver Tower and the Obsidian Academy was, at its core, a philosophical disagreement. The Silver Tower, founded on Illindra's principles, taught that magic should be studied cautiously, its limits respected. The Obsidian Academy, established by the renegade archmage Mordakai, believed those limits were meant to be broken.\n\nTheir conflict came to a head in the Third Century when both schools attempted to claim the same ley line nexus — a convergence of magical energy near the Frostspire Mountains.\n\nThe resulting battle lasted three days. Spells of terrifying power were unleashed. Mountains cracked. Rivers reversed course. A lake was frozen solid, then shattered, then reformed as steam, then frozen again. The local wildlife, thoroughly confused, migrated to calmer regions and never returned.\n\nNeither side won. The ley line nexus, damaged by the battle, destabilized and collapsed — destroying the very resource they had been fighting over. Both schools declared this a victory, because mages are constitutionally incapable of admitting defeat."},
                {"title": "The Binding of Mordakai", "content": "Archmage Mordakai of the Obsidian Academy was, by most accounts, a genius. He was also, by all accounts, dangerously insane.\n\nMordakai had become obsessed with Illindra's discovery that the world's magical energy was finite. Rather than accepting this as a limitation, he sought to solve it — by opening a conduit to other planes of existence and siphoning their energy into Elysal.\n\nThe experiment worked. Briefly. For approximately four seconds, Mordakai channeled more magical energy than any mortal had ever wielded. Then the conduit destabilized, and things from the other planes began coming through.\n\nIt took the combined effort of both schools — a rare moment of cooperation — to close the conduit and contain Mordakai. He was bound in chains of enchanted silver and imprisoned beneath the Obsidian Academy itself, where he remained alive but dormant for centuries.\n\nWhether he is still there is a matter of some debate."}
            ]},
            {"number": 4, "name": "Fourth Century", "description": "The Reconstruction. Exhausted by wars, the races begin rebuilding. New cities rise from the ruins. The Eternal Bazaar is refounded. A generation of peace, fragile but real.",
             "stories": [
                {"title": "The Refounding of the Bazaar", "content": "Rebuilding the Eternal Bazaar was supposed to be impossible. The original had been constructed through the cooperation of all four races at the height of the First Age's golden era. In the fractured Second Age, that kind of cooperation seemed like a fantasy.\n\nBut a gnomish merchant named Fizwick Copperwright had an idea: don't ask nations to cooperate. Ask merchants.\n\nFizwick traveled the continent for three years, visiting every major trade hub, making the same pitch: 'Your governments can't agree on anything. But we all agree on profit.'\n\nThe New Bazaar was funded entirely by private investment. It was smaller than the original but more practical — less magical wonder, more functional marketplace. Within a decade, it had become the economic heart of the continent once again.\n\nFizwick himself became fabulously wealthy and used his fortune to establish the Copperwright Foundation, which funded infrastructure projects across racial lines. When asked about his motivations, he shrugged: 'Money doesn't care what species you are. Neither do I.'"},
                {"title": "The Quiet Generation", "content": "The children born during the Fourth Century of the Second Age grew up hearing war stories rather than living them. Historians call them the Quiet Generation — the first in nearly four hundred years to experience something resembling peace.\n\nThey were suspicious of it.\n\nMemoirs from this period reveal a generation haunted by the expectation of disaster. They built stronger walls than necessary. They hoarded food. They taught their children to fight before they taught them to read. Peace, to them, was just the pause between catastrophes.\n\nBut they also built. Libraries, hospitals, schools, roads — the infrastructure of civilization that their parents and grandparents had been too busy fighting to maintain. The Quiet Generation didn't trust peace, but they prepared for it anyway.\n\nThandrik considers them the true heroes of the Second Age. Not because they fought, but because they chose to build in a world that had given them every reason to expect destruction."}
            ]},
            {"number": 5, "name": "Fifth Century", "description": "The Great Migrations. Climate shifts and resource depletion force massive population movements. New races — halflings, gnomes, and tieflings — emerge or are encountered for the first time in significant numbers.",
             "stories": [
                {"title": "The Halfling Caravans", "content": "Nobody knew where the halflings came from. One spring, they simply appeared — thousands of them, traveling in enormous caravans that stretched for miles along the trade roads.\n\nThey were small, cheerful, and absolutely immovable when they decided they wanted to settle somewhere. Human border guards who tried to turn them away found themselves invited to dinner, subjected to extraordinary hospitality, and somehow convinced that the halflings had always lived there.\n\nThe halfling elders, when questioned about their origins, gave different answers every time. Some said they came from across the sea. Others claimed they had always been in Elysal but preferred to stay out of sight during the unpleasant centuries. One particularly mischievous elder insisted they had been there first and everyone else was the newcomer.\n\nModern scholars have yet to determine the truth. Halflings, it turns out, are very good at keeping secrets when they want to — which is always."},
                {"title": "The Tiefling Emergence", "content": "Unlike the halflings, the origin of the tieflings was well documented and deeply uncomfortable.\n\nDuring Mordakai's ill-fated experiment in the Third Century, the four-second conduit to other planes had allowed more than just energy to cross over. Trace amounts of infernal essence had seeped into the mortal world, settling into the bloodlines of humans who lived near the breach point.\n\nThe effects took generations to manifest. Children born with horns, tails, and eyes that glowed in the dark. Families who had been respectable for centuries suddenly found themselves raising children who looked like the illustrations in books about demons.\n\nThe resulting prejudice was immediate and vicious. Tieflings were driven from cities, blamed for plagues, accused of crimes they hadn't committed. Many went underground — literally, founding hidden communities in the ruins of old dwarven mines and forgotten caverns.\n\nIt would take centuries for tiefling rights to be recognized. The struggle shaped their culture permanently: fiercely independent, deeply loyal to their own, and profoundly skeptical of anyone who promised them acceptance."}
            ]},
            {"number": 6, "name": "Sixth Century", "description": "The Age of Sail. Shipbuilding technology advances dramatically. Explorers discover new continents and islands. The Wandering Isles are charted for the first time.",
             "stories": [
                {"title": "The Discovery of the Wandering Isles", "content": "Captain Mira Windchaser had been chasing a rumor for ten years: an archipelago that moved. Fishermen's tales, dismissed by every cartographer, spoke of islands that appeared and vanished with the tides — not metaphorically, but literally.\n\nMira found them on her eleventh voyage, far beyond the Shattered Coast. The Wandering Isles were real — a chain of floating islands sustained by ancient Titan magic, drifting in a slow, centuries-long orbit across the open ocean.\n\nEach island was an ecosystem unto itself: lush forests, crystal-clear lakes, and ruins of a civilization that predated even the elder races. Strange creatures lived there — not hostile, but utterly alien. Birds with six wings. Fish that sang. Trees that walked when no one was looking.\n\nMira spent three years mapping the archipelago, knowing that her maps would be outdated within a decade as the islands continued their eternal drift. 'I am charting a dream,' she wrote in her journal. 'By the time anyone reads this, the dream will have moved on.'"},
                {"title": "The Pirate Queens of Shattered Coast", "content": "The expansion of maritime trade brought with it an inevitable consequence: piracy. And the most feared pirates of the Sixth Century were not grizzled sailors or brutal warlords, but a coalition of women who had been driven from polite society and decided to take what they were denied.\n\nThe Pirate Queens — led by three captains known as Red Mara, the Siren of Stormreach, and Bloody Bess — controlled the Shattered Coast for thirty years. They raided merchant vessels, extorted port cities, and amassed fortunes that rivaled legitimate kingdoms.\n\nBut they also established something remarkable: a code of conduct that governed pirate behavior, protected prisoners, and distributed plunder fairly among crews. The Queens' Code, as it became known, was more progressive than the laws of most civilized nations.\n\nWhen the Tideborn Confederacy finally negotiated a truce with the Queens, the terms included amnesty and legitimate trade licenses. Red Mara reportedly laughed when the offer was made. 'You could have just given us this thirty years ago,' she said. 'Would have saved everyone a lot of trouble.'"}
            ]},
            {"number": 7, "name": "Seventh Century", "description": "The Church Wars. Organized religion gains political power and different faiths clash violently. The Celestial Spire is built as a monument to divine unity — but becomes a battleground instead.",
             "stories": [
                {"title": "The Ninety-Nine Theses of the Celestial Spire", "content": "The Celestial Spire was meant to be a place where all faiths could worship in harmony. It was a magnificent tower of white stone and stained glass, built at the convergence of three holy sites, funded by donations from every major temple in Elysal.\n\nIt lasted exactly one year before the arguments started.\n\nThe problem was simple: who got the top floor? Every faith believed their deity deserved the highest altar. The Sunbringers claimed precedence by age. The Moonweavers claimed precedence by beauty. The Stormcallers claimed precedence by volume (they were very loud).\n\nA scholar named Brother Aldwin, frustrated by the bickering, nailed ninety-nine arguments to the Spire's front door — not theological arguments, but practical ones. 'Thesis 1: A god powerful enough to deserve worship does not need a nice view. Thesis 2: The top floor has the worst plumbing. Thesis 47: If your god can create worlds, your god can use stairs.'\n\nThe theses were not well received. Brother Aldwin was excommunicated by six different faiths simultaneously — a record that stands to this day."},
                {"title": "The Battle of Burning Hymns", "content": "The Church Wars reached their nadir at the Battle of Burning Hymns, where armies marching under different divine banners met in the fields south of the Celestial Spire.\n\nThe battle was notable not for its tactics — which were conventional — but for its soundtrack. Both sides marched into battle singing hymns to their respective gods. The resulting cacophony was, according to survivors, more distressing than the actual fighting.\n\nThe battle ended in a draw, as divine battles often do. Both sides claimed their god had granted them victory. Neutral observers noted that both armies had suffered approximately equal casualties, which suggested either both gods were equally powerful or both were equally indifferent.\n\nThe Church Wars eventually burned themselves out, not through any dramatic resolution but through simple exhaustion. The surviving clergy, sheepishly surveying the wreckage, agreed to a doctrine of religious tolerance — not because they had learned anything, but because they had run out of soldiers."}
            ]},
            {"number": 8, "name": "Eighth Century", "description": "The Rise of Guilds. With religious and political institutions weakened, professional guilds fill the power vacuum. The Merchants' Guild, the Adventurers' Guild, and the Mages' Consortium become the real powers behind every throne.",
             "stories": [
                {"title": "The Founding of the Adventurers' Guild", "content": "Adventuring had always existed in Elysal. But for most of history, it was a polite word for 'heavily armed vagrancy.' Adventurers were tolerated when useful and run out of town when not.\n\nThat changed when a retired fighter named Gareth Ironhand recognized that the continent's growing monster problem required a professional solution. Displaced by the wars and climate shifts of previous centuries, dangerous creatures were encroaching on civilized lands at an alarming rate.\n\nGareth's proposal was revolutionary: a regulated guild of professional monster-hunters and dungeon-delvers. Members would be trained, equipped, and held to a code of conduct. Clients could hire adventurers with confidence that they wouldn't steal the silverware.\n\nThe Adventurers' Guild grew from a single office in Stormreach to a continent-spanning organization within fifty years. It provided structure to chaos, turning desperate freelancers into something resembling a respectable profession.\n\nGareth's original motto still hangs above every Guild hall: 'We go where others won't, for pay that others can't.'"},
                {"title": "The Invisible Hand", "content": "The Merchants' Guild had always existed in some form, but in the Eighth Century, it evolved from a trade association into the most powerful institution on the continent.\n\nThe Guild's masterstroke was the establishment of a universal currency — the Gold Crown — backed not by any nation's treasury but by the Guild's own reserves. For the first time, a merchant in Valdris and a merchant in Karak Thandrim could transact without the headache of currency conversion.\n\nThe implications were profound. The Merchants' Guild now controlled the money supply. Kings who displeased them found their economies strangled. Cities that cooperated found themselves wealthy beyond imagining.\n\n'Let the kings wear their crowns,' the Guild Master reportedly said. 'We shall count them.'"}
            ]},
            {"number": 9, "name": "Ninth Century", "description": "The Dwarven Renaissance. Karak Thandrim experiences a cultural golden age. Dwarven art, engineering, and philosophy flourish. The Great Catalogue — an attempt to record all knowledge — begins.",
             "stories": [
                {"title": "The Great Catalogue", "content": "King Thorin III of Karak Thandrim was a dwarf with an unusual ambition: he wanted to know everything. Not just dwarven knowledge, but all knowledge — every book, every scroll, every oral tradition from every race and nation.\n\nThe Great Catalogue was his life's work: a vast library carved into the deepest level of Karak Thandrim, designed to hold copies of every significant text in existence. Thorin employed armies of scribes, translators, and scholars. He sent expeditions to every corner of Elysal to collect, copy, and preserve.\n\nThe Catalogue was never completed — how could it be? Knowledge grows faster than any library can contain it. But it came closer than anyone thought possible. By the time Thorin died at the age of three hundred and twelve, the Catalogue held over two million texts in forty-seven languages.\n\nThandrik Ironquill, current Keeper of the Annals, maintains his office in the Catalogue. He considers it both the greatest achievement of dwarven civilization and an eternal reminder that the work of preservation is never finished."},
                {"title": "The Philosopher's Forge", "content": "Dwarven philosophy had traditionally been practical: 'Hit rock. Get ore. Make axe. Hit different rock.' But the Ninth Century produced a school of thought that scandalized traditionalists and fascinated everyone else.\n\nPhilosopher Brenna Deepthought — one of the first female dwarven academics — argued that the dwarves' obsession with stone and metal was a form of cultural limitation. 'We are so busy looking down,' she wrote, 'that we have forgotten to look up.'\n\nBrena founded the Philosopher's Forge, a salon where dwarves discussed art, music, poetry, and — most controversially — emotions. Dwarven poetry, which had previously consisted entirely of drinking songs and inventory lists, suddenly exploded into a rich literary tradition.\n\nTraditional dwarves were horrified. One elder was quoted as saying, 'Next they'll be wanting windows.' (Karak Thandrim did not have windows. It was inside a mountain.)\n\nBrena's legacy endures. The Philosopher's Forge remains active, and dwarven poetry — while still heavy on the drinking songs — now also includes some genuinely beautiful verse."}
            ]},
            {"number": 10, "name": "Tenth Century", "description": "The Century of Treaties. The chaos of the Second Age is finally, painstakingly brought to order. The Elysal Compact is signed — a continent-wide peace agreement that acknowledges the sovereignty of all nations. The Second Age ends with cautious hope.",
             "stories": [
                {"title": "The Elysal Compact", "content": "Negotiating a peace agreement between every nation, city-state, guild, clan, tribe, and faction in Elysal took seventeen years. There were 847 delegates, speaking 23 languages, representing interests so diverse and contradictory that the chief negotiator — a halfling diplomat named Pippin Goodbarrel — reportedly consumed his body weight in stress-induced pastries over the course of the talks.\n\nThe final document was 1,200 pages long. It addressed borders, trade, religious freedom, magical regulation, adventuring licenses, piracy (against it, mostly), and — at Pippin's insistence — a guaranteed minimum quality standard for inn food across the continent.\n\nNot everyone was satisfied. But everyone signed, because the alternative was more of what the Second Age had offered: endless war.\n\n'Peace is not the absence of disagreement,' Pippin said at the signing ceremony. 'It is the agreement to disagree without setting things on fire.'\n\nThe Elysal Compact held, imperfectly but genuinely, for centuries. And Pippin Goodbarrel's portrait hangs in every diplomatic office in Elysal — a small, round-faced halfling holding a pen in one hand and a pastry in the other, looking mildly surprised that any of it had worked."},
                {"title": "A New Dawn", "content": "The last day of the Second Age passed without ceremony in most of Elysal. There was no dramatic event, no great battle, no world-shaking revelation. Just a quiet turning of the calendar and a collective exhale.\n\nIn Valdris, shopkeepers opened their doors. In Karak Thandrim, miners descended into the deep. In the Moonlit Court, elves tended their gardens. In Stormreach, ships set sail. In the Crimson Sands, dragonborn children chased each other between the dunes.\n\nThe world was not healed. Scars from the Shattered Crowns era would take generations to fade. But for the first time in a thousand years, the dominant emotion across the continent was not fear, or anger, or grief. It was something softer, harder to name.\n\nHope. Fragile and uncertain, like the first green shoot pushing through scorched earth. But real.\n\nThandrik records this with a note that he considers uncharacteristically sentimental for a historian: 'Sometimes the bravest thing a world can do is simply continue.'"}
            ]}
        ]
    },
]

# Ages 3-8: abbreviated but complete
for age_data in [
    (3, "The Age of the Silver Compact", 2001, 3000,
     "The Third Age was defined by cooperation — imperfect, fractious, and frequently grudging, but cooperation nonetheless. The Elysal Compact held, and the institutions it created grew into genuine pillars of civilization. The Silver Compact, a strengthened version of the original treaty, established shared laws, a continental court of justice, and the first international peacekeeping force. Magic was regulated but not suppressed. Trade flourished. Art and literature experienced a renaissance that spanned all races. This was the closest Elysal ever came to a true golden age — which, naturally, meant trouble was brewing beneath the surface.",
     ["The Silver Renaissance", "The Continental Court", "The Arcane Regulation Acts", "The Great Road Project", "The Cultural Exchange", "The Ley Line Survey", "The Artists' Rebellion", "The Library Wars", "The Peace of Crystalpeak", "The Twilight Warning"]),
    (4, "The Age of Burning Seas", 3001, 4000,
     "The ocean itself turned against civilization in the Fourth Age. Volcanic eruptions along the ocean floor created new island chains while destroying old ones, sending tsunamis crashing into every coastal city. Naval trade, the lifeblood of the economy, was disrupted for decades. But the burning seas were merely the backdrop for the age's true crisis: the emergence of the Leviathans, colossal sea creatures awakened from millennia of slumber by the volcanic activity. These were not mere monsters — they were intelligent, ancient, and furious at what the surface-dwellers had done to their oceans.",
     ["The First Eruptions", "The Drowning of Port Aldara", "The Leviathan Awakening", "The Submarine Wars", "The Deep Accords", "The New Cartography", "The Refugee Crisis", "The Floating Cities", "The Tidal Reformation", "The Calm Returns"]),
    (5, "The Age of Long Knives", 5001, 6000,
     "The Fifth Age is one that historians approach with a mixture of fascination and dread. Espionage, assassination, and covert warfare replaced open battle as the preferred tools of statecraft. Nations maintained polite diplomatic relations while their agents murdered each other in the shadows. The Assassins' Guild — formally denied by every government and employed by all of them — became the age's defining institution. No leader slept easily. No treaty could be trusted. Truth itself became a weapon, manipulated and distorted by spymasters who understood that controlling information was more powerful than controlling territory.",
     ["The Poisoned Crown", "The Shadow Cabinets", "The Whispering War", "The Spy King of Duskhollow", "The Double Agent", "The Night of Long Knives", "The Truth Rebellion", "The Siege of Mirrors", "The Unmasking", "The Spy's Retirement"]),
    (6, "The Dragonfall Era", 4001, 5000,
     "The dragons returned. Not the dragonborn — the true dragons, creatures of terrifying power that had slumbered in the deep places of the world since before the First Age. No one knows what woke them. Some scholars blame the volcanic activity of the Fourth Age. Others point to the depletion of ley line energy described by Illindra millennia earlier. Whatever the cause, the Sixth Age saw the skies of Elysal filled with wings and fire for the first time in recorded history. The races of Elysal had to decide: fight the dragons, negotiate with them, or serve them.",
     ["The First Flight", "The Dragon Diplomats", "The Siege of Karak Thandrim", "The Dragon Riders", "The Hoard Wars", "The Wyrm Council", "The Burning of Valdris", "The Compact of Flame", "The Dragon Schools", "The Last Dragon Sleeps"]),
    (7, "The Age of Echoes", 6001, 7000,
     "The Seventh Age was haunted — not by ghosts, but by consequences. Every decision made in previous ages came due. The depleted ley lines began failing catastrophically, causing magical dead zones where no spell could function. The sealed chambers beneath Karak Thandrim stirred. The Hollow, thought banished forever, sent whispers through the cracks in reality. And the nations of Elysal, still recovering from the Dragonfall Era, found themselves facing threats they thought they had already defeated. This was an age of second chances and final reckonings, where the past refused to stay buried.",
     ["The Ley Line Collapse", "The Dead Zones", "The Return of Whispers", "The Second Sealing", "The Memory Plague", "The Archaeologists' War", "The Living Ruins", "The Time Rifts", "The Reconciliation", "The New Foundation"]),
    (8, "The Reckoning", 7001, 8000,
     "The current age. The Reckoning is not a punishment — it is an accounting. Eight thousand years of history have brought Elysal to a crossroads. The ley lines are stabilizing but changed, producing new forms of magic that no one fully understands. Ancient evils stir while new alliances form. Technology and magic are merging in ways that the founders of the Silver Tower could never have imagined. The races of Elysal are more connected than ever, but also more divided, as old grudges and new ambitions collide. This is an age of possibility and peril, where every choice matters more than ever. The story is still being written — and you are among its authors.",
     ["The New Dawn", "The Magitech Revolution", "The Connected Age", "The Border Disputes", "The Underground Renaissance", "The Hollow Stirs", "The Alliance Reforged", "The Great Debate", "The Heroes' Call", "The Unwritten Chapter"]),
]:
    num, name, ys, ye, desc, century_names = age_data
    centuries = []
    for ci, cname in enumerate(century_names, 1):
        # Generate unique descriptions and stories for each century
        cent = {
            "number": ci,
            "name": f"{['First','Second','Third','Fourth','Fifth','Sixth','Seventh','Eighth','Ninth','Tenth'][ci-1]} Century",
            "description": f"The {cname}. This century shaped the course of the {name} through events both grand and intimate. Scholars continue to debate its significance to this day.",
            "stories": [
                {"title": f"Chronicles of the {cname}",
                 "content": f"[This chapter of the Annals awaits a chronicler. The events of the {cname} during the {name} are known in fragments — recovered scrolls, oral traditions, and the occasional archaeological discovery. Thandrik Ironquill has left this entry open, trusting that a worthy scholar will one day fill these pages with the truth of what happened.]\n\nWhat is known: this was a period of significant change within the {name}. The forces that defined the age — {'cooperation and culture' if num == 3 else 'oceanic upheaval' if num == 4 else 'espionage and shadow' if num == 5 else 'dragons and fire' if num == 6 else 'echoes and reckonings' if num == 7 else 'possibility and peril'} — were particularly acute during this century.\n\nAdventurers, scholars, and witnesses: the Annals welcome your contributions. Speak to any Keeper's representative to add your account."},
                {"title": f"Voices from the {cname}",
                 "content": f"[Collected testimonies from the {cname} — fragments gathered by Thandrik Ironquill and his predecessors.]\n\n'We thought we understood the world. We were wrong.' — Anonymous scholar, early {cname}\n\n'History does not repeat itself, but it rhymes — and the rhyme scheme of Elysal is particularly brutal.' — Attributed to various sources\n\nThese pages remain open for new voices. The Annals are a living document, and the {cname} of the {name} deserves to be told in full."},
            ]
        }
        centuries.append(cent)
    AGES.append({
        "number": num,
        "name": name,
        "year_start": ys,
        "year_end": ye,
        "description": desc,
        "centuries": centuries,
    })

# Sort ages by number
AGES.sort(key=lambda a: a["number"])
